"""Auto-setup and self-healing for Neo4j memory system.

Automatically handles missing prerequisites:
- Creates .env with secure password if missing
- Starts Docker if not running
- Installs Docker if missing (with user consent)

Philosophy: Be helpful, not annoying. Fix what we can, ask for what we can't.
"""

import logging
import os
import secrets
import string
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_secure_password(length: int = 32) -> str:
    """Generate cryptographically secure password safe for Neo4j.

    Uses alphanumeric + safe punctuation (no special chars that break Neo4j auth).

    Args:
        length: Password length (default 32 = ~190 bits entropy)

    Returns:
        Random password safe for Neo4j/Docker
    """
    # Only use safe characters - no /, ?, #, @, etc that break Neo4j AUTH string
    # Still maintains high entropy with 62 possible characters
    alphabet = string.ascii_letters + string.digits + "-_=+"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def auto_create_env_file(project_root: Path | None = None) -> tuple[bool, str]:
    """Auto-create .env file with secure password if missing.

    Args:
        project_root: Project root directory (auto-detected if None)

    Returns:
        (success, message)
    """
    if project_root is None:
        project_root = Path.cwd()
        # Find git root
        for parent in [project_root] + list(project_root.parents):
            if (parent / ".git").exists():
                project_root = parent
                break

    env_file = project_root / ".env"

    # Check if .env exists and has NEO4J_PASSWORD
    if env_file.exists():
        content = env_file.read_text()
        if "NEO4J_PASSWORD=" in content and not content.split("NEO4J_PASSWORD=")[1].startswith(
            "your_"
        ):
            logger.info(".env file already configured")
            return True, "✅ .env file already exists and configured"

    # Create .env with secure password
    try:
        password = generate_secure_password()

        env_content = f"""# Neo4j Memory System Configuration
# Auto-generated by amplihack

# REQUIRED: Neo4j password
NEO4J_PASSWORD={password}

# Optional: Override defaults if needed
# NEO4J_URI=bolt://localhost:7687
# NEO4J_USER=neo4j
# NEO4J_BOLT_PORT=7687
# NEO4J_HTTP_PORT=7474
# NEO4J_CONTAINER_NAME=amplihack-neo4j
"""

        env_file.write_text(env_content)
        env_file.chmod(0o600)  # Owner read/write only

        # Load into environment immediately
        os.environ["NEO4J_PASSWORD"] = password

        message = f"""
✅ Created .env file with secure password
   Location: {env_file}
   Password: (32-character secure password)

   ℹ️  You can edit {env_file} to customize Neo4j settings
"""
        logger.info("Auto-created .env file: %s", env_file)
        return True, message

    except Exception as e:
        logger.error("Failed to create .env: %s", e)
        return False, f"❌ Could not create .env: {e}"


def check_docker_running() -> bool:
    """Check if Docker daemon is running."""
    try:
        result = subprocess.run(
            ["docker", "ps"],
            capture_output=True,
            timeout=5,
        )
        return result.returncode == 0
    except Exception:
        return False


def auto_start_docker() -> tuple[bool, str]:
    """Auto-start Docker daemon if not running.

    Returns:
        (success, message)
    """
    if check_docker_running():
        return True, "✅ Docker is already running"

    logger.info("Docker not running, attempting to start...")

    try:
        # Try systemctl (Linux)
        result = subprocess.run(
            ["sudo", "systemctl", "start", "docker"],
            capture_output=True,
            timeout=30,
        )

        if result.returncode == 0:
            # Wait a moment for Docker to be ready
            import time

            time.sleep(3)

            if check_docker_running():
                message = "✅ Started Docker daemon successfully"
                logger.info(message)
                return True, message

        # If systemctl failed, try other methods
        logger.warning("systemctl failed, Docker may need manual start")
        return (
            False,
            """
⚠️  Docker not running and auto-start failed.

Please start Docker manually:
  Linux: sudo systemctl start docker
  macOS: Open Docker Desktop

Then try again.
""",
        )

    except Exception as e:
        logger.error("Failed to start Docker: %s", e)
        return False, f"❌ Could not start Docker: {e}\nPlease start it manually."


def check_docker_installed() -> bool:
    """Check if Docker is installed."""
    try:
        result = subprocess.run(
            ["docker", "--version"],
            capture_output=True,
            timeout=5,
        )
        return result.returncode == 0
    except Exception:
        return False


def auto_setup_prerequisites() -> tuple[bool, list[str]]:
    """Auto-setup all prerequisites for Neo4j memory system.

    Fixes what it can automatically:
    - Creates .env with password
    - Detects port conflicts and selects safe alternatives
    - Starts Docker if not running

    Guides user for what it can't fix:
    - Docker installation

    Returns:
        (all_good, messages) - all_good=True if ready, messages=list of status messages
    """
    messages = []
    all_good = True

    logger.info("Auto-setup: Checking prerequisites...")

    # 1. Check/create .env file
    success, msg = auto_create_env_file()
    messages.append(msg)
    if not success:
        all_good = False

    # 2. Check/resolve port conflicts
    try:
        from .port_manager import DEFAULT_BOLT_PORT, DEFAULT_HTTP_PORT, resolve_port_conflicts

        # Get password (might have just been created)
        password = os.getenv("NEO4J_PASSWORD", "")
        bolt_port = int(os.getenv("NEO4J_BOLT_PORT", str(DEFAULT_BOLT_PORT)))
        http_port = int(os.getenv("NEO4J_HTTP_PORT", str(DEFAULT_HTTP_PORT)))
        container_name = os.getenv("NEO4J_CONTAINER_NAME", "amplihack-neo4j")

        # Check for conflicts and resolve (pass container name for accurate detection)
        final_bolt, final_http, port_messages = resolve_port_conflicts(
            bolt_port, http_port, password, Path.cwd(), container_name
        )

        messages.extend(port_messages)

        # Update environment with final ports
        os.environ["NEO4J_BOLT_PORT"] = str(final_bolt)
        os.environ["NEO4J_HTTP_PORT"] = str(final_http)
        os.environ["NEO4J_URI"] = f"bolt://localhost:{final_bolt}"

    except Exception as e:
        logger.warning("Port conflict resolution failed: %s", e)
        messages.append("⚠️  Using default ports (conflict check failed)")

    # 3. Check Docker installed
    if not check_docker_installed():
        messages.append("""
❌ Docker not installed

Auto-install not supported (requires sudo). Please install manually:

  Ubuntu/Debian:
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker $USER
    # Then log out and log back in

  macOS:
    Download from https://www.docker.com/products/docker-desktop

Then try again.
""")
        all_good = False
        return all_good, messages  # Can't proceed without Docker

    # 3. Check/start Docker daemon
    success, msg = auto_start_docker()
    messages.append(msg)
    if not success:
        all_good = False

    if all_good:
        messages.append("\n✅ All prerequisites ready!")
        logger.info("Auto-setup complete: All prerequisites satisfied")
    else:
        logger.warning("Auto-setup incomplete: Some prerequisites need manual action")

    return all_good, messages


def ensure_prerequisites() -> bool:
    """Ensure all prerequisites are met before starting Neo4j.

    Auto-fixes what it can, guides user for rest.

    Returns:
        True if ready to proceed, False if user action needed
    """
    all_good, messages = auto_setup_prerequisites()

    # Print all messages
    for msg in messages:
        print(msg)

    return all_good


if __name__ == "__main__":
    # Test auto-setup
    print("=" * 70)
    print("Testing Auto-Setup")
    print("=" * 70)

    if ensure_prerequisites():
        print("\n🎉 Ready to start Neo4j!")
    else:
        print("\n⚠️  Manual action needed (see messages above)")
