# Default Workflow Recipe
# Converted from amplihack's DEFAULT_WORKFLOW.md (22 steps)
# This is the standard workflow for feature development, bug fixes, and refactoring

name: "default-workflow"
description: "Standard 22-step workflow for feature development, bug fixes, and refactoring. Follows amplihack philosophy: ruthless simplicity, zero-BS implementation, test-driven development."
version: "1.1.0"
author: "amplihack team"
tags: ["development", "workflow", "feature", "bugfix", "refactoring"]

context:
  task_description: "{{user_task}}"
  branch_prefix: "feat"
  require_issue: true
  require_worktree: true

recursion:
  max_depth: 5
  max_total_steps: 50

# Phase 1: Requirements & Planning
stages:
  requirements:
    description: "Clarify requirements, create issue, setup workspace"
    steps:
      - id: "step-0-preparation"
        name: "Workflow Preparation"
        type: agent
        agent: "foundation:zen-architect"
        prompt: |
          MANDATORY WORKFLOW PREPARATION - DO NOT SKIP

          Read and understand the complete 22-step workflow. Create a comprehensive plan for:

          Task: {{task_description}}

          You MUST:
          1. Understand all 22 steps before starting
          2. Create detailed todos for ALL steps (0-21)
          3. Identify which steps need which specialized agents
          4. Mark each step complete ONLY when truly done
          5. Task is NOT complete until Step 21 is marked complete

          Anti-patterns to avoid:
          - DO NOT skip to implementation after reading requirements
          - DO NOT consider "PR created" as completion
          - DO NOT omit mandatory review steps (10, 16-17)

          Output your understanding and the complete todo list.

      - id: "step-1-workspace"
        name: "Prepare Workspace"
        type: bash
        command: |
          echo "=== Step 1: Prepare Workspace ==="
          git fetch --all
          git status
          echo "Workspace ready for development"

      - id: "step-2-clarify"
        name: "Rewrite and Clarify Requirements"
        type: agent
        agent: "amplihack:prompt-writer"
        prompt: |
          STEP 2: Rewrite and Clarify Requirements

          Original task: {{task_description}}

          You must:
          1. Identify explicit user requirements that CANNOT be optimized away
          2. Clarify task requirements with automatic task classification
          3. Remove ambiguity from the task description
          4. Define clear success criteria
          5. Document acceptance criteria

          Output a clarified requirements document with:
          - Clear problem statement
          - Success criteria
          - Acceptance criteria
          - Constraints and dependencies
        outputs:
          clarified_requirements: "{{result}}"

      - id: "step-3-issue"
        name: "Create GitHub Issue"
        type: bash
        command: |
          echo "=== Step 3: Create GitHub Issue ==="
          # This would use gh issue create in a real scenario
          echo "Issue creation requires: clear problem description, requirements, constraints, success criteria"
          echo "Use: gh issue create --title 'Title' --body 'Description' --label 'enhancement'"
        when: "{{require_issue}}"

      - id: "step-4-branch"
        name: "Setup Worktree and Branch"
        type: bash
        command: |
          echo "=== Step 4: Setup Worktree and Branch ==="
          # Branch naming: feat/issue-XXX-brief-description
          echo "Create worktree: git worktree add ./worktrees/{{branch_prefix}}/branch-name -b branch-name"
          echo "Push with tracking: git push -u origin branch-name"
        when: "{{require_worktree}}"

  design:
    description: "Research, design architecture, write documentation"
    approval_required: true
    approval_message: "Requirements phase complete. Review before proceeding to design?"
    steps:
      - id: "step-5-research"
        name: "Research and Design"
        type: agent
        agent: "foundation:zen-architect"
        prompt: |
          STEP 5: Research and Design

          Task: {{task_description}}
          Clarified Requirements: {{steps.step-2-clarify.clarified_requirements}}

          INVESTIGATION-FIRST: If the codebase is unfamiliar/complex, investigate first.

          Design the solution:
          1. Review existing codebase patterns
          2. Design solution architecture
          3. Identify API contracts needed
          4. Consider security requirements
          5. Document module specifications
          6. Create detailed implementation plan
          7. Identify risks and dependencies

          Output a comprehensive design document.
        outputs:
          design_document: "{{result}}"

      - id: "step-6-documentation"
        name: "Retcon Documentation"
        type: agent
        agent: "amplihack:documentation-writer"
        prompt: |
          STEP 6: Retcon Documentation Writing

          Design: {{steps.step-5-research.design_document}}

          Write documentation for the finished feature AS IF IT ALREADY EXISTS.
          This is "retcon documentation" - the documentation for the feature as we want it to be.

          Write ONLY the documentation, not the code.
          The architect will review this to ensure alignment.
        outputs:
          documentation: "{{result}}"

      - id: "step-7-tests"
        name: "Test Driven Development - Write Tests First"
        type: agent
        agent: "amplihack:tester"
        prompt: |
          STEP 7: Test Driven Development

          Design: {{steps.step-5-research.design_document}}
          Documentation: {{steps.step-6-documentation.documentation}}

          Following TDD methodology, write FAILING tests based on the design.
          These tests define the expected behavior before implementation.

          Output test specifications that will guide the implementation.
        outputs:
          test_specs: "{{result}}"

  implementation:
    description: "Implement, refactor, review before commit"
    approval_required: true
    approval_message: "Design phase complete. Proceed to implementation?"
    steps:
      - id: "step-8-implement"
        name: "Implement the Solution"
        type: agent
        agent: "foundation:modular-builder"
        prompt: |
          STEP 8: Implement the Solution

          Design: {{steps.step-5-research.design_document}}
          Documentation: {{steps.step-6-documentation.documentation}}
          Test Specs: {{steps.step-7-tests.test_specs}}

          Implement from specifications:
          1. Follow the architecture design
          2. Make failing tests pass iteratively
          3. Ensure all requirements are met
          4. Update documentation as needed

          CRITICAL: No stubs, no TODOs, no placeholders. Zero-BS implementation.
        outputs:
          implementation: "{{result}}"

      - id: "step-9-refactor"
        name: "Refactor and Simplify"
        type: agent
        agent: "amplihack:cleanup"
        prompt: |
          STEP 9: Refactor and Simplify

          Implementation: {{steps.step-8-implement.implementation}}
          Original Requirements: {{steps.step-2-clarify.clarified_requirements}}

          CRITICAL: Preserve original user requirements while simplifying.

          1. Remove unnecessary abstractions (not explicitly requested)
          2. Eliminate dead code
          3. Simplify complex logic
          4. Ensure single responsibility principle
          5. Verify NO placeholders remain

          VALIDATE: All explicit user requirements still preserved.
        outputs:
          refactored_code: "{{result}}"

      - id: "step-10-review-precommit"
        name: "Review Pass Before Commit"
        type: agent
        agent: "amplihack:reviewer"
        prompt: |
          STEP 10: Review Pass Before Commit - MANDATORY

          Code: {{steps.step-9-refactor.refactored_code}}

          Comprehensive code review:
          1. Check code quality and standards
          2. Verify philosophy compliance
          3. Ensure adequate test coverage
          4. Identify potential improvements
          5. Verify ZERO: TODOs, stubs, swallowed exceptions, unimplemented functions

          Output detailed review findings.
        outputs:
          review_findings: "{{result}}"

      - id: "step-11-feedback"
        name: "Incorporate Review Feedback"
        type: agent
        agent: "foundation:modular-builder"
        prompt: |
          STEP 11: Incorporate Review Feedback

          Review Findings: {{steps.step-10-review-precommit.review_findings}}
          Current Code: {{steps.step-9-refactor.refactored_code}}

          Address all review feedback and update documentation as needed.
        outputs:
          updated_code: "{{result}}"

  testing:
    description: "Run tests, pre-commit hooks, local testing"
    steps:
      - id: "step-12-precommit"
        name: "Run Tests and Pre-commit Hooks"
        type: bash
        command: |
          echo "=== Step 12: Run Tests and Pre-commit Hooks ==="
          # Check if pre-commit config exists
          if [ -f .pre-commit-config.yaml ]; then
            echo "Pre-commit config found"
            pre-commit run --all-files || echo "Pre-commit checks need attention"
          fi
          # Run tests
          pytest --tb=short || echo "Tests need attention"

      - id: "step-13-local-testing"
        name: "Mandatory Local Testing"
        type: agent
        agent: "amplihack:tester"
        prompt: |
          STEP 13: Mandatory Local Testing - NOT in CI

          CRITICAL: Test all changes locally in realistic scenarios BEFORE committing.
          Test like a user would use the feature - outside-in.

          Test checklist:
          1. Simple use cases - Basic functionality
          2. Complex use cases - Edge cases, longer operations
          3. Integration points - External dependencies
          4. No regressions - Existing functionality still works

          Document test results for the PR description.
        outputs:
          test_results: "{{result}}"

  pr_creation:
    description: "Commit, push, create draft PR"
    approval_required: true
    approval_message: "Testing complete. Ready to create PR?"
    steps:
      - id: "step-14-commit"
        name: "Commit and Push"
        type: agent
        agent: "foundation:git-ops"
        prompt: |
          STEP 14: Commit and Push

          Task: {{task_description}}
          Test Results: {{steps.step-13-local-testing.test_results}}

          Create a detailed commit:
          1. Stage all changes
          2. Write detailed commit message
          3. Reference issue number
          4. Describe what changed and why
          5. Push to remote branch
        outputs:
          commit_info: "{{result}}"

      - id: "step-15-draft-pr"
        name: "Open Pull Request as Draft"
        type: bash
        command: |
          echo "=== Step 15: Open Pull Request as Draft ==="
          echo "Create draft PR: gh pr create --draft --title 'Title' --body 'Description' 2>&1 | cat"
          echo "Link to GitHub issue, write comprehensive description"
          echo "Include test plan and results"

  review:
    description: "PR review, feedback implementation, philosophy check"
    approval_required: true
    approval_message: "Draft PR created. Ready for review cycle?"
    steps:
      - id: "step-16-pr-review"
        name: "Review the PR"
        type: agent
        agent: "amplihack:reviewer"
        prompt: |
          STEP 16: Review the PR - MANDATORY DO NOT SKIP

          Comprehensive PR review:
          1. Code quality and standards
          2. Security review
          3. Philosophy compliance
          4. Test coverage
          5. Post review comments on PR
          6. Identify improvements
          7. ZERO: TODOs, stubs, swallowed exceptions

          This step is REQUIRED FOR ALL PRs.
        outputs:
          pr_review: "{{result}}"

      - id: "step-17-pr-feedback"
        name: "Implement Review Feedback"
        type: agent
        agent: "foundation:modular-builder"
        prompt: |
          STEP 17: Implement Review Feedback - MANDATORY DO NOT SKIP

          PR Review: {{steps.step-16-pr-review.pr_review}}

          Address ALL review feedback:
          1. Review all feedback comments carefully
          2. Implement changes
          3. Push updates to PR
          4. Respond to review comments
          5. Ensure all tests still pass

          Unaddressed feedback means the review process was pointless.
        outputs:
          feedback_implementation: "{{result}}"

      - id: "step-18-philosophy"
        name: "Philosophy Compliance Check"
        type: agent
        agent: "amplihack:philosophy-guardian"
        prompt: |
          STEP 18: Philosophy Compliance Check

          Final philosophy verification:
          1. Ruthless simplicity achieved?
          2. Bricks & studs pattern followed?
          3. Zero-BS implementation?
          4. All tests passing?
          5. Documentation complete and accurate?
        outputs:
          philosophy_check: "{{result}}"

      - id: "step-19-final-cleanup"
        name: "Final Cleanup and Verification"
        type: agent
        agent: "amplihack:cleanup"
        prompt: |
          STEP 19: Final Cleanup and Verification

          Original Requirements: {{steps.step-2-clarify.clarified_requirements}}

          CRITICAL: Provide original requirements for context.

          Final quality pass:
          1. Review all changes for philosophy compliance
          2. Remove temporary artifacts
          3. Eliminate unnecessary complexity
          4. Verify module boundaries clean
          5. ZERO dead code or stubs

          FINAL CHECK: All explicit user requirements preserved.
        outputs:
          final_cleanup: "{{result}}"

  merge:
    description: "Convert to ready, ensure mergeable"
    approval_required: true
    approval_message: "Review cycle complete. Ready to finalize PR?"
    steps:
      - id: "step-20-ready"
        name: "Convert PR to Ready for Review"
        type: bash
        command: |
          echo "=== Step 20: Convert PR to Ready for Review ==="
          echo "Convert: gh pr ready 2>&1 | cat"
          echo "Only convert when: all feedback addressed, philosophy verified, truly ready"

      - id: "step-21-mergeable"
        name: "Ensure PR is Mergeable"
        type: agent
        agent: "amplihack:ci-diagnostic-workflow"
        prompt: |
          STEP 21: Ensure PR is Mergeable - TASK COMPLETION POINT

          Final checks:
          1. CI status - all checks passing?
          2. Merge conflicts resolved?
          3. All review comments addressed?
          4. PR approved?

          If CI fails, diagnose and fix.
          
          Notify that PR is ready to merge.

          THIS IS THE COMPLETION POINT. Task is NOT done until this step completes.
        outputs:
          merge_status: "{{result}}"
