"""PR generation and creation for completed agent work.

Generates PR titles, bodies, and creates draft PRs via gh CLI.

Philosophy:
- Conventional commit format for titles
- Rich PR bodies with context and checklist
- Draft PRs for review before merge
- Safe gh CLI wrapper

Public API:
    PRCreator: Main PR creation class
"""

import json
import logging
import subprocess
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)


class PRCreator:
    """Creates pull requests for completed agent work.

    Generates rich PR descriptions with:
    - Conventional commit titles
    - Comprehensive body with context
    - Links to parent issue
    - Test results and evidence
    """


    def generate_title(
        self,
        issue_number: int,
        issue_title: str
    ) -> str:
        """Generate PR title following conventional commits.

        Args:
            issue_number: Issue number
            issue_title: Issue title

        Returns:
            Formatted PR title
        """
        # Detect commit type from issue title
        title_lower = issue_title.lower()

        if any(word in title_lower for word in ["fix", "bug", "error"]):
            prefix = "fix:"
        elif any(word in title_lower for word in ["doc", "readme", "guide"]):
            prefix = "docs:"
        elif any(word in title_lower for word in ["test", "testing"]):
            prefix = "test:"
        elif any(word in title_lower for word in ["refactor", "cleanup", "improve"]):
            prefix = "refactor:"
        else:
            prefix = "feat:"

        return f"{prefix} {issue_title} (Issue #{issue_number})"

    def generate_body(
        self,
        issue_number: int,
        parent_issue: int,
        summary: str,
        test_results: Optional[Dict[str, Any]] = None
    ) -> str:
        """Generate PR body with context and checklist.

        Args:
            issue_number: Sub-issue number
            parent_issue: Parent orchestration issue
            summary: Implementation summary
            test_results: Optional test results dict

        Returns:
            Formatted PR body markdown
        """
        body = f"""## Summary
{summary}

## Context
This PR addresses issue #{issue_number} as part of the larger orchestration effort in #{parent_issue}.

**Generated by**: Parallel Task Orchestrator (automated agent)
**Parent Epic**: #{parent_issue}

## Changes
<!-- Detailed description of changes made -->

Closes #{issue_number}

## Testing
"""

        if test_results:
            body += f"""
### Test Results
- **Tests Passed**: {test_results.get('passed', 'N/A')}
- **Tests Failed**: {test_results.get('failed', 'N/A')}
- **Coverage**: {test_results.get('coverage', 'N/A')}%
"""
        else:
            body += """
- [ ] Unit tests added/updated
- [ ] Integration tests passing
- [ ] Manual testing completed
"""

        body += """

## Documentation
- [ ] Code comments added
- [ ] README updated (if needed)
- [ ] CHANGELOG updated (if applicable)

## Checklist
- [ ] Code follows project style guidelines
- [ ] Self-review completed
- [ ] Tests passing locally
- [ ] No new warnings introduced
- [ ] Documentation updated

---
*This PR was generated by the Parallel Task Orchestrator*
"""

        return body

    def validate_branch_exists(self, branch_name: str) -> bool:
        """Validate that branch exists on remote.

        Args:
            branch_name: Branch name to check

        Returns:
            True if branch exists
        """
        try:
            result = subprocess.run(
                ["git", "branch", "-r", "--list", f"*{branch_name}"],
                capture_output=True,
                text=True,
                timeout=10
            )
            return result.returncode == 0 and branch_name in result.stdout
        except Exception:
            return False

    def create_pr(
        self,
        branch_name: str,
        title: str,
        body: str,
        draft: bool = True,
        base_branch: str = "main"
    ) -> Dict[str, Any]:
        """Create PR via gh CLI.

        Args:
            branch_name: Source branch name
            title: PR title
            body: PR body markdown
            draft: Create as draft PR
            base_branch: Target base branch

        Returns:
            Dict with pr_number and url

        Raises:
            RuntimeError: If PR creation fails
        """
        cmd = [
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", base_branch,
            "--head", branch_name
        ]

        if draft:
            cmd.append("--draft")

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode != 0:
                error_msg = result.stderr.lower()
                if "branch" in error_msg:
                    raise RuntimeError(f"PR creation failed: branch '{branch_name}' not found on remote")
                raise RuntimeError(f"PR creation failed: {result.stderr}")

            # Parse gh CLI JSON output
            try:
                pr_data = json.loads(result.stdout)
                return {
                    "number": pr_data.get("number"),
                    "url": pr_data.get("url", ""),
                    "state": pr_data.get("state", "draft" if draft else "open")
                }
            except json.JSONDecodeError:
                # Fallback if not JSON
                return {
                    "number": None,
                    "url": result.stdout.strip(),
                    "state": "draft" if draft else "open"
                }

        except subprocess.TimeoutExpired:
            raise RuntimeError("PR creation timed out")
        except FileNotFoundError:
            raise RuntimeError("gh CLI not found - please install GitHub CLI")
        except Exception as e:
            raise RuntimeError(f"PR creation failed: {e}")

    def add_labels(
        self,
        pr_number: int,
        labels: List[str]
    ) -> None:
        """Add labels to PR.

        Args:
            pr_number: PR number
            labels: List of label names
        """
        try:
            subprocess.run(
                ["gh", "pr", "edit", str(pr_number), "--add-label", ",".join(labels)],
                capture_output=True,
                timeout=10
            )
        except Exception as e:
            # Non-fatal - labels are optional
            logger.debug(f"Failed to add labels to PR #{pr_number}: {e}", exc_info=True)

    def create_batch(
        self,
        agents: List[Dict[str, Any]],
        parent_issue: int
    ) -> List[Dict[str, Any]]:
        """Create PRs for batch of completed agents.

        Args:
            agents: List of agent dicts with issue_number, branch_name, summary
            parent_issue: Parent orchestration issue

        Returns:
            List of PR creation results
        """
        results = []

        for agent in agents:
            issue_number = agent["issue_number"]
            branch_name = agent["branch_name"]
            summary = agent.get("summary", "Implementation complete")

            try:
                # Generate title and body
                title = self.generate_title(
                    issue_number,
                    agent.get("issue_title", f"Issue {issue_number}")
                )
                body = self.generate_body(
                    issue_number,
                    parent_issue,
                    summary
                )

                # Create PR
                pr_result = self.create_pr(
                    branch_name=branch_name,
                    title=title,
                    body=body,
                    draft=True
                )

                results.append({
                    "issue_number": issue_number,
                    "pr_number": pr_result["number"],
                    "pr_url": pr_result.get("url", ""),
                    "success": True
                })

            except Exception as e:
                results.append({
                    "issue_number": issue_number,
                    "error": str(e),
                    "success": False
                })

        return results


__all__ = ["PRCreator"]
