flowchart TD
    IO0[/"json write<br/>n=339"/]
    IO1[("json read<br/>n=250")]
    IO2[/"text write<br/>n=135"/]
    IO3[("text read<br/>n=97")]
    IO4[("yaml read<br/>n=15")]
    IO5[/"yaml write<br/>n=6"/]
    IO6[("toml read<br/>n=2")]
    DB7[("kuzu<br/>ops: 188")]
    DB8[("sqlite<br/>ops: 59")]
    DB9[("neo4j<br/>ops: 44")]
    DB10[("falkordb<br/>ops: 2")]
    NET11("Network I/O<br/>n=23")
    T0{{"_create_similarity_edges"}}
    T1{{"import_from_json"}}
    T2{{"handler"}}
    T3{{"_upload_package"}}
    T4{{"update_bundle"}}
    T5{{"main"}}
    T6{{"run_harness"}}
    T7{{"_run_teaching_subprocess"}}
    T8{{"run_l7_teaching_eval"}}
    T9{{"run_single_level"}}
