flowchart TD
    IO0[/"json write<br/>n=1686"/]
    IO1[("json read<br/>n=1287")]
    IO2[("text read<br/>n=583")]
    IO3[/"text write<br/>n=575"/]
    IO4[("yaml read<br/>n=136")]
    IO5[/"yaml write<br/>n=45"/]
    IO6[("toml read<br/>n=9")]
    IO7[/"csv write<br/>n=1"/]
    DB8[("neo4j<br/>ops: 62")]
    DB9[("sqlite<br/>ops: 100")]
    DB10[("kuzu<br/>ops: 321")]
    DB11[("falkordb<br/>ops: 2")]
    NET12("Network I/O<br/>n=56")
    T0{{"save_session_marker"}}
    T1{{"main"}}
    T2{{"test_cmd_enable"}}
    T3{{"test_cmd_import_merge"}}
    T4{{"test_cmd_import_replace"}}
    T5{{"condense_xml"}}
    T6{{"generate_config"}}
    T7{{"test_cli_output_json_format"}}
    T8{{"test_config_generation_and_serialization"}}
    T9{{"test_config_with_custom_parameters_persistence"}}