graph LR
    S0(["subprocess.run"])
    S1(["uv"])
    S2(["subprocess.Popen"])
    S3(["&lt;dynamic&gt;"])
    S4(["pytest"])
    S5(["gh"])
    S6(["git"])
    B0{{"flask :None (http)"}}
    B1{{"flask :None (http)"}}
    B2{{"flask :None (http)"}}
    B3{{"uvicorn :None (http)"}}
    B4{{"uvicorn :None (http)"}}
    FN0["microsoft_sdk"]
    FN0 --> S0
    FN1["auto_update"]
    FN1 --> S1
    FN1 --> S2
    FN1 --> S3
    FN1 --> S2
    FN2["cli"]
    FN2 --> S4
    FN3["distributor"]
    FN3 --> S5
    FN3 --> S0
    FN3 --> S0
    FN3 --> S5
    FN3 --> S0
    FN3 --> S6
    FN3 --> S6
    FN3 --> S6
    FN3 --> S6
    FN3 --> S0
    FN3 --> S0
    FN3 --> S0
    FN3 --> S6
    FN3 --> S6
    FN4["filesystem_packager"]
    FN4 --> S3
    FN5["repository_creator"]
    FN5 --> S5
    FN5 --> S5
    FN5 --> S0
    FN5 --> S0
    FN5 --> S5
    FN5 --> S5
    FN5 --> S6
    FN5 --> S5
    FN6["update_manager"]
    FN6 --> S6