"""
Configuration constants for Auto-Mode

Contains all configurable values that were previously hardcoded as magic numbers.
This allows for easier maintenance and customization of the auto-mode system.
"""

# Session Management Constants
DEFAULT_SESSION_TIMEOUT_MINUTES = 60
DEFAULT_MAX_SESSIONS_PER_USER = 5
DEFAULT_CLEANUP_INTERVAL_MINUTES = 10

# SDK Integration Constants
DEFAULT_CONNECTION_TIMEOUT_SECONDS = 10.0
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_DELAY_SECONDS = 2.0
DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 30.0
DEFAULT_API_KEY_MIN_LENGTH = 10

# Orchestrator Constants
DEFAULT_ANALYSIS_INTERVAL_SECONDS = 30.0
DEFAULT_SESSION_TIMEOUT_MINUTES_ORCHESTRATOR = 60
DEFAULT_MAX_CONCURRENT_SESSIONS = 10
DEFAULT_SDK_RETRY_ATTEMPTS = 3
DEFAULT_SDK_TIMEOUT_SECONDS = 10.0
DEFAULT_NEXT_CYCLE_DELAY_SECONDS = 30.0
DEFAULT_ERROR_SLEEP_SECONDS = 5.0

# Quality Gates Constants
DEFAULT_MIN_CONFIDENCE_THRESHOLD = 0.5
DEFAULT_COOLDOWN_MINUTES = 5
DEFAULT_MAX_TRIGGERS_PER_SESSION = 3
DEFAULT_FRUSTRATION_COOLDOWN_MINUTES = 10
DEFAULT_QUALITY_THRESHOLD = 0.5
DEFAULT_INTERVENTION_CONFIDENCE_THRESHOLD = 0.5

# Analysis Engine Constants
DEFAULT_MIN_MESSAGES_FOR_ANALYSIS = 3
DEFAULT_MAX_SIMILAR_REQUESTS = 3
DEFAULT_MAX_GOALS_CONSIDERATION = 3
DEFAULT_LOW_COMPLETION_RATE_THRESHOLD = 0.3
DEFAULT_HIGH_LEARNING_MESSAGE_RATIO = 0.5
DEFAULT_KEY_TERMS_SIMILARITY_BOOST = 0.3
DEFAULT_ERROR_IMPACT_MULTIPLIER = 0.3
DEFAULT_LOW_COMPLETION_THRESHOLD = 0.5
DEFAULT_BASIC_QUESTIONS_RATIO = 0.5
DEFAULT_CONVERSATION_ACTIVITY_THRESHOLD = 10
DEFAULT_CONVERSATION_ACTIVITY_MULTIPLIER = 1.5
DEFAULT_RECENT_ANALYSES_COUNT = 3
DEFAULT_LOW_QUALITY_THRESHOLD = 0.5
DEFAULT_MAX_ANALYSIS_FREQUENCY_MULTIPLIER = 3.0
DEFAULT_SENTIMENT_BASE_CONFIDENCE = 0.5
DEFAULT_SENTIMENT_CONFIDENCE_INCREMENT = 0.1
DEFAULT_SENTIMENT_MAX_CONFIDENCE = 0.9

# Time-based Constants (in seconds)
SECONDS_PER_MINUTE = 60
HOURS_PER_DAY = 24
SECONDS_PER_DAY = HOURS_PER_DAY * SECONDS_PER_MINUTE * 60

# Synthesis Constants
DEFAULT_SYNTHESIS_SIMULATION_DELAY = 0.3