graph LR
    F0["constants<br/>refs: 45"]
    F1["models<br/>refs: 38"]
    F2["models<br/>refs: 28"]
    F3["models<br/>refs: 28"]
    F4["exceptions<br/>refs: 28"]
    F5["models<br/>refs: 26"]
    F6["base<br/>refs: 23"]
    F7["xpia_defense_interface<br/>refs: 22"]
    F8["uvx_models<br/>refs: 18"]
    F9["__init__<br/>refs: 17"]
    F10["exceptions<br/>refs: 17"]
    F11["base<br/>refs: 16"]
    F12["coordinator<br/>refs: 15"]
    F13["settings<br/>refs: 14"]
    F14["language_definitions<br/>refs: 14"]
    F15["event_bus<br/>refs: 13"]
    F16["long_horizon_memory<br/>refs: 13"]
    F17["monitoring<br/>refs: 13"]
    F18["conversion<br/>refs: 12"]
    F19["Reference<br/>refs: 11"]
    F20["multi_agent_template<br/>refs: 10"]
    F21["azure_errors<br/>refs: 10"]
    F22["xpia_patterns<br/>refs: 10"]
    F23["defensive<br/>refs: 10"]
    F24["queries<br/>refs: 10"]
    F25["controller<br/>refs: 9"]
    F26["reviewer_voting<br/>refs: 9"]
    F27["install<br/>refs: 9"]
    F28["cli_handlers<br/>refs: 9"]
    F29["azure_unified_integration<br/>refs: 9"]
    F9 --> F27
    F9 --> F13
    F25 --> F0
    F25 --> F15
    F27 --> F9
    F27 --> F13
    F12 --> F3
    F21 --> F4
    F21 --> F17
    F18 --> F21
    F18 --> F4
    F18 --> F5
    F18 --> F17
    F17 --> F4
    F17 --> F21
    F13 --> F9

    click F0 "../ast-lsp-bindings/" "View AST bindings"