"""Triage report generation."""

from typing import Any


def generate_triage_report(
    pr_number: int,
    pr_data: dict[str, Any],
    compliance: dict[str, Any],
    labels: dict[str, str],
    unrelated: dict[str, Any],
) -> str:
    """Generate comprehensive triage report.

    Args:
        pr_number: PR number
        pr_data: PR data
        compliance: Workflow compliance results
        labels: Priority and complexity labels
        unrelated: Unrelated changes detection

    Returns:
        Markdown report
    """
    report_parts = [
        "## 🤖 PM Architect PR Triage Analysis",
        "",
        f"**PR**: #{pr_number}",
        f"**Title**: {pr_data['title']}",
        f"**Author**: @{pr_data['author']['login']}",
        f"**Branch**: `{pr_data['headRefName']}` → `{pr_data['baseRefName']}`",
        "",
        "---",
        "",
    ]

    # Workflow Compliance
    report_parts.extend(
        [
            "### ✅ Workflow Compliance (Steps 11-12)",
            "",
        ]
    )

    if compliance.get("overall_compliant"):
        report_parts.extend(
            [
                "✅ **COMPLIANT** - PR meets workflow requirements",
                "",
                f"**Step 11 (Review)**: {'✅ Completed' if compliance.get('step11_completed') else '❌ Incomplete'}",
                f"- {compliance.get('step11_evidence', 'N/A')}",
                "",
                f"**Step 12 (Feedback)**: {'✅ Completed' if compliance.get('step12_completed') else '❌ Incomplete'}",
                f"- {compliance.get('step12_evidence', 'N/A')}",
                "",
            ]
        )
    else:
        report_parts.extend(
            [
                "❌ **NON-COMPLIANT** - PR needs workflow completion",
                "",
                f"**Step 11 (Review)**: {'✅ Completed' if compliance.get('step11_completed') else '❌ Incomplete'}",
                f"- {compliance.get('step11_evidence', 'N/A')}",
                "",
                f"**Step 12 (Feedback)**: {'✅ Completed' if compliance.get('step12_completed') else '❌ Incomplete'}",
                f"- {compliance.get('step12_evidence', 'N/A')}",
                "",
                "**Blocking Issues:**",
            ]
        )
        for issue in compliance.get("blocking_issues", []):
            report_parts.append(f"- {issue}")
        report_parts.append("")

    # Priority and Complexity
    report_parts.extend(
        [
            "### 🏷️ Classification",
            "",
            f"**Priority**: `{labels.get('priority', 'MEDIUM')}`",
            f"- {labels.get('priority_reasoning', 'N/A')}",
            "",
            f"**Complexity**: `{labels.get('complexity', 'MODERATE')}`",
            f"- {labels.get('complexity_reasoning', 'N/A')}",
            "",
        ]
    )

    # Unrelated Changes
    report_parts.extend(
        [
            "### 🔍 Change Scope Analysis",
            "",
        ]
    )

    if unrelated.get("has_unrelated_changes"):
        report_parts.extend(
            [
                "⚠️ **UNRELATED CHANGES DETECTED**",
                "",
                f"**Primary Purpose**: {unrelated.get('primary_purpose', 'N/A')}",
                "",
                "**Unrelated Changes:**",
            ]
        )
        for purpose in unrelated.get("unrelated_purposes", []):
            report_parts.append(f"- {purpose}")
        report_parts.extend(
            [
                "",
                "**Affected Files:**",
            ]
        )
        for file_path in unrelated.get("unrelated_files", []):
            report_parts.append(f"- `{file_path}`")
        report_parts.extend(
            [
                "",
                f"**Recommendation**: {unrelated.get('recommendation', 'N/A')}",
                "",
            ]
        )
    else:
        report_parts.extend(
            [
                "✅ **FOCUSED CHANGES** - All changes are related to PR purpose",
                "",
                f"**Purpose**: {unrelated.get('primary_purpose', 'N/A')}",
                "",
            ]
        )

    # Recommendations
    if compliance.get("recommendations"):
        report_parts.extend(
            [
                "### 💡 Recommendations",
                "",
            ]
        )
        for rec in compliance.get("recommendations", []):
            report_parts.append(f"- {rec}")
        report_parts.append("")

    # Statistics
    report_parts.extend(
        [
            "---",
            "",
            "### 📊 Statistics",
            "",
            f"- **Files Changed**: {len(pr_data['files'])}",
            f"- **Comments**: {len(pr_data['comments'])}",
            f"- **Reviews**: {len(pr_data['reviews'])}",
            "",
        ]
    )

    # Footer
    report_parts.extend(
        [
            "---",
            "",
            "*🤖 Generated by PM Architect automation using Claude Agent SDK*",
            "",
        ]
    )

    return "\n".join(report_parts)
